### ISSUE TITLE
When was skippatches removed?

### ISSUE THREAD

**Issue by gitscosh** [Kalanyr/gogrepoc#45]
I recently updated from an older version of your script, and when I tried to run it today with my typical `py -2 gogrepoc.py download -skipgalaxy -skippatches -lang en -os windows mac` I got the unrecognized argument message. Sure enough, searching through the python script, it has been removed. The old version (I don't remember which one, but I have the file downloaded) included it. Is there another way to accomplish the same thing? Why was skippatches removed?

**Comment by Kalanyr** [comment]
I suspect you were using a fork, I don't think this project has ever had
that functionality (it did have something similar but that functionality
doesn't work now that galaxy installers have been removed).

 GOG doesn't actually clearly distinguish patches from other installers in
a machine readable fashion (it's sorta doable with some pattern matching
and heuristics) so I've been leery to implement it in the past but I think
I'm gonna have to bite that bullet.

**Comment by gitscosh** [comment]
That is SUPER weird. Because I looked in the header of the file and the only info is this:

```
__appname__ = 'gogrepo.py'
__author__ = 'eddie3,kalynr'
__version__ = 'k0.3a'
__url__ = 'https://github.com/kalanyr/gogrepo'
```

I looked at all the current forks off of your project and can't seem to find which one it was. Oh, well. Sorry for the confusion!

**Comment by loki1985** [comment]
I would ask for this functionality, the amount of wasted space because of patches is enormous, for me probably > 100GB. Cyberpunk alone has > 15GB patch files.

At least for windows patches it should be quite possible, all files appear to start with "patch_" and end with ".exe" (or ".bin" additionally for really big patches, like Cyberpunk).

If you would consider merging this i would be more than happy to provide a PR.

**Comment by gitscosh** [comment]
-skipfiles does this just fine and already exists.
