### ISSUE TITLE
How do I find the id of a game?

### ISSUE THREAD

**Issue by v-dawg** [Kalanyr/gogrepoc#64]
I am trying to download Baldurs Gate 3 with the script from my library, but I cannot find its id.
How can I find it?

**Comment by Job76** [comment]
it might be the "slug" name under details... I tested downloading Avernum: Escape From the Pit using the slug name 
python gogrepoc.py download -dryrun -id avernum_escape_from_the_pit I:\GOG\

**Comment by Job76** [comment]
python gogrepoc.py download -dryrun -id 1420630484 I:\GOG\ gives the same result so both ID and slug name seems to work
(I do not own Baldurs Gate 3)

**Comment by Kalanyr** [comment]
Yeah the game IDs and short names are mostly interchangeable, for this
purpose. If you already have stuff downloaded the easiest thing to do is
check the existing folder name (and the numeric ID is in the !info.txt)

Also I'd recommend using -ids over -id (there's no actual difference
because -id is just an alias for -ids but it's a relic of a past when you
could only specific one at a time, and it may get removed at some point)

**Comment by v-dawg** [comment]
Thank you guys :)
